languageCode = "en-us"
title = "Boarding End to End 2018"
baseURL = "http://localhost:1313/"
theme = "dopetrope"

[params]
    subtitle = "Howdy. This is Dopetrope."
    subtitleline2 = "A responsive template by HTML5 UP"

[params.intro]
    icon1 = "fa-road"
    title1 = "John O'Groats to Lands End"
    description1 = "Nisl amet dolor sit ipsum veroeros sed blandit consequat veroeros et magna tempus."

    icon2 = "fa-calendar"
    title2 = "7th August 2018"
    description2 = "Nisl amet dolor sit ipsum veroeros sed blandit consequat veroeros et magna tempus."

    icon3 = "fa-heart"
    title3 = "Myton Hospice"
    description3 = "Nisla amet dolor sit ipsum veroeros sed blandit consequat veroeros et magna tempus."

    buttonlink1 = "http://www.virginmoneygiving.com/boardingendtoend"
    buttontext1 = "Donate"

    buttonlink2 = "https://www.facebook.com/boardingendtoend"
    buttontext2 = "Learn More"

[params.footer]
    title1 = "Blandit nisl adipiscing"

    title2 = "What's this all about?"
    imagelink2 = "#"
    imageurl2 = "images/footer.png"
    description2 = "This is Dopetrope a free, fully responsive HTML5 site template by AJ for HTML5 UP It's released for free under the Creative Commons Attribution license so feel free to use it for any personal or commercial project – just don't forget to credit us!"
    buttonlink2 = "#"
    buttontext2 = "Find out more"

    title3 = "Tempus consequat"

    title4 = "Ipsum et phasellus"

    title5 = "Vitae tempor lorem"

[params.blog]
    title = "The Van"
    viewalltext = "View All"
    postsperpage = "6"
    foldername = "van"

[params.social]
    facebook = "https://www.facebook.com/boardingendtoend"
    twitter = ""
    dribbble = ""
    linkedin = ""
    googleplus = ""

[params.address]
    line1 = ""
    line2 = ""
    line3 = ""

[params.contact]
    email = ""
    phone = ""

[params.settings]
    googleanalytics = "UA-96256914-1"
    disqus = "be2e-dev"